const partiesMap = {
  'AP': 'Arbeiderpartiet',
  'D': 'Demokratene',
  'DK': 'De kristne',
  'DLF': 'Det Liberale Folkepartiet',
  'FM': 'Folkemakten',
  'FrP': 'Fremskrittspartiet',
  'H': 'Høyre',
  'KrF': 'Kristelig Folkeparti',
  'KP': 'Kystpartiet',
  'KS': 'Kristent Samlingsparti',
  'MDG': 'Miljøpartiet De Grønne',
  'MO': 'Mot oljeboring',
  'NKP': 'Norges Kommunistiske Parti',
  'PP': 'Pensjonistpartiet',
  'P': 'Piratpartiet',
  'R': 'Rødt',
  'SaP': 'Samfunnspartiet',
  'SP': 'Senterpartiet',
  'StA': 'Sykehus til Alta',
  'SV': 'Sosialistisk Venstreparti',
  'V': 'Venstre',
};